FROM golang:1.22-alpine AS builder

ARG SERVICE_NAME

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /service ./service/${SERVICE_NAME}/cmd/

FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY --from=builder /service .

EXPOSE 8000

CMD ["./service"]
